FROM demoregistry.dataman-inc.com/library/centos7-base:20160602202509
MAINTAINER yqguo yqguo@dataman-inc.com

ENV CGO_ENABLED "0 go build -v"
COPY omega-es/omega-es /
COPY omega-es/sql /sql
ENTRYPOINT ["./omega-es"]

#demoregistry.dataman-inc.com/shurenyun/centos7-omega-es:tag
